version: "3.8"
services:
  mysql-server:
    container_name: mysql-container
    image: mysql:latest
    env_file:
      - app.env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 20
#    volumes:
#      - spring-batch-mysql:/var/lib/mysql
    networks:
      - spring-batch-network
    restart: on-failure
  server:
    container_name: spring-batch-demo-container
    depends_on:
      mysql-server:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.env
    ports:
      - "8080:8080"
    networks:
      - spring-batch-network
    restart: on-failure
networks:
  spring-batch-network:
    name: spring-batch-network
    driver: bridge
#volumes:
#  spring-batch-mysql: